Add note about using TypeScript with autocasting.
Esri/jsapi-resources pull request #303
Opened 2021-05-25 23:22 UTC by andygup

This adds temporary notices about current limitations in TypeScript when using it with autocasting. It's mainly aimed at devs who are copying API samples or code snippets, since many of them use autocasting.

Also includes other minor touchups in the READMEs.

2021-05-25 23:44 UTC, dasa requested changes

2021-05-25 23:44 UTC, dasa commented on 4.x/typescript/README.md
> +* [Type definitions for Dojo][4].
Should we remove this?

2021-05-25 23:44 UTC, dasa commented on 4.x/webpack/demo/README.md
> +  },
This doesn't match the heading.

2021-05-25 23:51 UTC, andygup commented on 4.x/typescript/README.md
> +* [Type definitions for Dojo][4].
Good catch, removed.

2021-05-25 23:51 UTC, andygup commented on 4.x/webpack/demo/README.md
> +  },
Fixed, thanks.

2021-05-26 15:57 UTC, dasa approved these changes
👍🏻

2021-05-26 17:28 UTC, merged