refactor(metrics): separate build size calculation
Esri/jsapi-resources pull request #376
Opened 2022-02-11 22:06 UTC by benelan

- Moves the code that calculates the build sizes into a separate script
- The separate script can be used by end users to calculate their build sizes, as demonstrated in the rollup sample

2022-02-11 23:06 UTC, andygup requested changes
LGTM!

2022-02-11 23:36 UTC, benelan commented on .github/scripts/build-size.js
> +    ).stdout.trim() / 1e6 // convert bytes to megabytes
Can you provide a bit more explanation? It already catches errors and logs them. For example this is what is displayed when I delete the angular build npm script 
![image](https://user-images.githubusercontent.com/10986395/153684738-53569245-0c28-4595-b856-9f621e5d9cd3.png)

2022-02-12 00:17 UTC, andygup commented on .github/scripts/build-size.js
> +    ).stdout.trim() / 1e6 // convert bytes to megabytes
Oh okay. I didn't know if the errors bubbled up when using `await exec()`, or if you had to explicitly declare it. I did see the try/catch block but I had a vague recollection of running into issues on that in the past.

2022-02-12 00:43 UTC, andygup commented on .github/scripts/build-size.js
> +    ).stdout.trim() / 1e6 // convert bytes to megabytes
In other words, will the try/catch capture errors within the build process, e.g. like a typescript compile error? It's easy enough to test the existing code pattern.

```
const { stdout, stderr } = await exec(...buildStep...);
console.error(stderr);
```
versus

```
try {
   await exec(...buildStep...) 
}
catch(err) {
   console.error(err);
}

2022-02-12 00:46 UTC, benelan commented on .github/scripts/build-size.js
> +    ).stdout.trim() / 1e6 // convert bytes to megabytes
Because a TS compile error would be logged to the console with a non-zero exit code, so I don't see why it wouldn't be caught

2022-02-12 00:46 UTC, andygup commented on .github/scripts/build-size.js
> +    ).stdout.trim() / 1e6 // convert bytes to megabytes
SGTM.

2022-02-12 02:09 UTC, merged