chore: update README and CONTRIBUTING
Esri/jsapi-resources pull request #486
Opened 2023-09-20 22:35 UTC by andygup

This PR updates the main README and CONTRIBUTING files:
* Reorganize and reword
* Include a TOC for the ESM samples
* Make section headers more descriptive
* Add additional context and clarifications, where needed

/cc @bsvensson

2023-09-20 23:30 UTC, dasa requested changes

2023-09-20 23:30 UTC, dasa commented on CONTRIBUTING.md
> +For anything else in this repo, feel free to report issues before submitted a pull request.
```suggestion
For anything else in this repo, feel free to report issues before submitting a pull request.
```

2023-09-20 23:30 UTC, dasa commented on README.md
> +If you have set OAuthInfo's `popup` property to `true`, you'll need to host a callback page on your server. This repo contains an [example callback page](./oauth/README.md). For more information, vis
```suggestion
If you have set OAuthInfo's `popup` property to `true`, you'll need to host a callback page on your server. This repo contains an [example callback page](./oauth/). For more information, visit the Maps SDK's [Access secure resources(https://developers.arcgis.com/javascript/latest/secure-resources/)] guide topic.
```

It might be better to not link to the README since then you can't easily see the callback page.

2023-09-21 19:33 UTC, dasa approved these changes
👍🏻

2023-09-21 19:36 UTC, odoe approved these changes
Looking good

2023-09-21 19:57 UTC, merged