Mg/add component readme
Esri/jsapi-resources pull request #516
Opened 2024-06-20 22:14 UTC by manugadde

Introduced a comprehensive README for the component-samples directory.

2024-06-20 22:36 UTC, omarkawach requested changes

2024-06-20 22:36 UTC, omarkawach commented on component-samples/README.md
> +- `@arcgis/charts-components`
```suggestion
This directory contains samples that demonstrate how to use web components from the ArcGIS Maps SDK for JavaScript with various frameworks, module bundlers, and build tools. There are three component packages available:
 
- Map components
- Coding components
- Charts components (beta)
```

2024-06-20 22:36 UTC, omarkawach commented on component-samples/README.md
> +These packages can be accessed through the ArcGIS CDN or npm. To install npm, visit [https://www.npmjs.com/get-npm](https://www.npmjs.com/get-npm).
```suggestion
Components from the SDK can be accessed through the ArcGIS CDN or npm. To install npm, visit [https://www.npmjs.com/get-npm](https://www.npmjs.com/get-npm).
```

2024-06-20 22:36 UTC, omarkawach commented on component-samples/README.md
> +Each component directory includes samples using CDN and ES module formats, with support for various frameworks, module bundlers, and build tools.
```suggestion
```

2024-06-20 22:52 UTC, omarkawach approved these changes

2024-06-21 16:54 UTC, andygup approved these changes
👍

2024-06-21 18:43 UTC, merged