chore: update map and coding component README with pure ESM approach
Esri/jsapi-resources pull request #526
Opened 2024-08-02 21:55 UTC by manugadde

Updates map and coding component vite sample README files to include instructions and examples for using the components with pure ESM. 
The following changes have been made:
- Added a section in the Map Components README on using the components using:`Lazy loading` and  `pure ESM`.
- Added a section in the Coding Components README on using the coding and calcite components using: `Lazy loading` and  `pure ESM`.
- Provided code examples to guide users on setting the asset path and importing components using ESM.

2024-08-07 18:53 UTC, omarkawach requested changes
Please apply the README suggestions to all the READMEs.

Some samples will need to be updated, like how ArcadeEditor.tsx had the imports in it, it should be moved to index.tsx for clarity.

2024-08-07 18:53 UTC, omarkawach commented on component-samples/coding-components/samples/react/README.md
> +To register all the components once, use the following approach:
```suggestion
The JavaScript Maps SDK also offers a convenience pattern useful for quick testing and prototyping. You can register all components at once using the following approach:
```

2024-08-07 18:53 UTC, omarkawach commented on component-samples/coding-components/samples/react/README.md
> +Recommended to use this ES modules (ESM) via the ArcGIS CDN way of importing only for testing and prototyping.
```suggestion
```

2024-08-07 18:53 UTC, omarkawach commented on component-samples/coding-components/samples/react/README.md
> +For more details on registering components, please refer to the [ArcGIS for JavaScript API documentation](https://developers.arcgis.com/javascript/latest/get-started-npm/#components).
```suggestion
For more details on using the SDK, please refer to the [ArcGIS Maps SDK for JavaScript documentation](https://developers.arcgis.com/javascript/latest/get-started-overview/).
```

2024-08-07 18:53 UTC, omarkawach commented on component-samples/coding-components/samples/react/src/index.tsx
> +setCalciteComponentsAssetPath("https://js.arcgis.com/calcite-components/2.8.0/assets");
```suggestion
// Individual imports for each component
import "@arcgis/coding-components/dist/components/arcgis-arcade-editor";
import "@esri/calcite-components/dist/components/calcite-scrim";

import { ArcgisArcadeEditor } from "@arcgis/coding-components-react";
import { CalciteScrim } from "@esri/calcite-components-react";
```

You'll have to update `react/src/components/ArcadeEditor.tsx`

You don't need to set an asset path when individually importing components, we pick up CDN hosted assets by default.

2024-08-07 18:53 UTC, omarkawach commented on component-samples/coding-components/samples/react/README.md
> +// Replace the imports in main.js
```suggestion
// Replace the individual imports with defineCustomElements()
```

2024-08-08 15:13 UTC, andygup approved these changes
👍 LGTM. Before merging, be sure to remove the `draft` label so that the zip files get rebuilt.

2024-08-09 22:22 UTC, omarkawach approved these changes
LGTM! I updated the React sample comments a bit since the imports sometimes live in a different file.

2024-08-09 22:54 UTC, merged