chore(map and coding components): update react samples to use v19
Esri/jsapi-resources pull request #548
Opened 2024-12-27 00:06 UTC by manugadde

This PR updates the `@arcgis/component-samples/map-components` and `@arcgis/component-samples/coding-components` to use React 19 and Angular 19

2025-01-02 16:43 UTC, dasa commented on component-samples/coding-components/samples/react/package.json
> +    "@esri/calcite-components": "^3.0.0-next",
Were these changes intended?

2025-01-07 00:24 UTC, andygup requested changes
Looks good overall, just needs a few small dependency updates.

2025-01-07 00:24 UTC, andygup commented on component-samples/map-components/samples/react/package.json
> +    "@arcgis/core": "^4.32.0-next.20241226",
Also switch these deps to production.

2025-01-07 00:24 UTC, andygup commented on component-samples/map-components/samples/angular/package.json
> +    "@arcgis/core": "^4.32.0-next.20241226",
Switch these deps to production.

2025-01-08 18:41 UTC, manugadde commented on component-samples/coding-components/samples/react/package.json
> +    "@esri/calcite-components": "^3.0.0-next",
Updated

2025-01-08 19:03 UTC, dasa approved these changes
👍🏻

2025-01-08 19:03 UTC, dasa commented on component-samples/map-components/samples/angular/package.json
> +   "@angular-devkit/build-angular": "^19.0.5",
```suggestion
    "@angular-devkit/build-angular": "^19.0.5",
```

2025-01-08 19:08 UTC, andygup approved these changes
Looks good!

2025-01-08 22:40 UTC, omarkawach approved these changes
This was a confusing PR for me to pull for review lol 

![image](https://github.com/user-attachments/assets/588e8e31-2160-4ec8-8d6e-826b12f04fd1)

Because our web components are not React components, you have to use `onarcgis...` event names instead of `onArcgis...`

2025-01-08 22:40 UTC, omarkawach commented on component-samples/coding-components/samples/react/package.json
> +    "typescript": "~5.6.2",
Is this necessary? We don't have any typescript files in this sample.

2025-01-08 22:40 UTC, omarkawach commented on component-samples/coding-components/samples/angular/src/app/app.component.ts
>  import { CommonModule } from "@angular/common";
This line is still needed?

2025-01-08 23:05 UTC, manugadde commented on component-samples/coding-components/samples/angular/src/app/app.component.ts
>  import { CommonModule } from "@angular/common";
Yes, `CommonModule`, which provides `NgIf`, `NgFor`, and other commonly used directives, has to be included in the imports array of the @Component decorator, otherwise throwing error.

2025-01-08 23:07 UTC, merged